### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by sanny13** [nmenon/powertool#2]
Hi, 
I have try Building with mpsse i have getting 
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lftdi
 error 
Can you please tell me  what is dependencies for that?
Note: I have already install
apt-get install libftdi-dev and apt-get install libftdi1
I am waiting for you replies

Thanks 
Sanny

**Comment by nmenon** [comment]
are you cross compiling and trying to use local PC's libftdi? that i have no idea to make work.

**Comment by arashed31** [comment]
Try libftdi1-dev, I believe that worked for me.

**Comment by nmenon** [comment]
closing if there are no further comments.
